### ISSUE TITLE
Attribute "per_page" Has Incorrect Validation

### ISSUE THREAD

**Issue by raphaelsander** [marcosmatioli/ragnarok-wiki#19]
Hi,

The **"per_page"** attribute in the API has incorrect validation, accepting values **equal to or less than 0**.
These values must be greater than 0 and limited by 100.

In case of values **equal to or less than 0**, the **status code must be 422**, a 422 status code indicates that the server was unable to process the request because it contains invalid data.

**Comment by marcosmatioli** [comment]
Hi,

I understood, if values equal to or less than zero, the website return status code 422.

All right, all right. Lets take care about this point and search for one solution for this.

Thanks for appoint this bug @raphaelsander !

**Comment by raphaelsander** [comment]
Hi @marcosmatioli and @Cicero-Henrique,

Could you review this PR?
Let me merge.
